# ########################################################################
#
# Copyright 2022 White Magic Software, Ltd.
#
# Creates a container image that can run ConTeXt to typeset documents.
#
# ########################################################################

FROM alpine:latest
ENV ENV="/etc/profile"
ENV PROFILE=/etc/profile
ENV CONTEXT_HOME=/opt/context
ENV FONT_DIR=/usr/share/fonts/user
ENV DOC_DIR=/root/text
ENV IMAGE_DIR=/root/images
ENV THEME_DIR=/root/themes
ENV INSTALL_DIR=/opt

RUN \
  apk --update add --no-cache fontconfig curl && \
  mkdir -p "$FONT_DIR" "$DOC_DIR" "$IMAGE_DIR" "$THEME_DIR" "$INSTALL_DIR"

# ########################################################################
#
# Download and install fonts
#
# ########################################################################
WORKDIR $FONT_DIR

# Carlito (Calibri replacement)
ADD "https://github.com/googlefonts/carlito/raw/main/fonts/ttf/Carlito-Regular.ttf" "Carlito-Regular.ttf"
ADD "https://github.com/googlefonts/carlito/raw/main/fonts/ttf/Carlito-Bold.ttf" "Carlito-Bold.ttf"
ADD "https://github.com/googlefonts/carlito/raw/main/fonts/ttf/Carlito-Italic.ttf" "Carlito-Italic.ttf"
ADD "https://github.com/googlefonts/carlito/raw/main/fonts/ttf/Carlito-BoldItalic.ttf" "Carlito-BoldItalic.ttf"

# Libre Baskerville
ADD "https://github.com/googlefonts/Libre-Baskerville/blob/master/fonts/ttf/LibreBaskerville-Regular.ttf" "LibreBaskerville-Regular.ttf"
ADD "https://github.com/googlefonts/Libre-Baskerville/blob/master/fonts/ttf/LibreBaskerville-Bold.ttf" "LibreBaskerville-Bold.ttf"
ADD "https://github.com/googlefonts/Libre-Baskerville/blob/master/fonts/ttf/LibreBaskerville-Italic.ttf" "LibreBaskerville-Italic.ttf"

# Open Sans Emoji
ADD "https://github.com/MorbZ/OpenSansEmoji/raw/master/OpenSansEmoji.ttf" "OpenSansEmoji.ttf"

# Underwood Quiet Tab
ADD "https://site.xavier.edu/polt/typewriters/Underwood_Quiet_Tab.ttf" "Underwood_Quiet_Tab.ttf"

# Archives
ADD "https://fonts.google.com/download?family=Courier%20Prime" "courier-prime.zip"
ADD "https://fonts.google.com/download?family=Inconsolata" "inconsolata.zip"
ADD "https://fonts.google.com/download?family=Nunito" "nunito.zip"
ADD "https://fonts.google.com/download?family=Roboto" "roboto.zip"
ADD "https://fonts.google.com/download?family=Roboto%20Mono" "roboto-mono.zip"
ADD "https://github.com/adobe-fonts/source-serif/releases/download/4.004R/source-serif-4.004.zip" "source-serif.zip"
ADD "https://www.omnibus-type.com/wp-content/uploads/Archivo-Narrow.zip" "archivo-narrow.zip"

# Unpack fonts, update system font cache
RUN \
  unzip -j -o courier-prime.zip "*.ttf" && \
  unzip -j -o inconsolata.zip "**/Inconsolata/*.ttf" && \
  unzip -j -o nunito.zip "static/*.ttf" && \
  unzip -j -o roboto.zip "*.ttf" && \
  unzip -j -o roboto-mono.zip "static/*.ttf" && \
  unzip -j -o source-serif.zip "source-serif-4.004/OTF/SourceSerif4-*.otf" && \
  unzip -j -o archivo-narrow.zip "Archivo-Narrow/otf/*.otf" && \
  fc-cache -f -v

# ########################################################################
#
# Configure environment variables
#
# ########################################################################
RUN \
  echo "export CONTEXT_HOME=\"$CONTEXT_HOME\"" >> $PROFILE && \
  echo "export PATH=\"\$PATH:\$CONTEXT_HOME/tex/texmf-linuxmusl/bin\"" >> $PROFILE && \
  echo "export OSFONTDIR=\"/usr/share/fonts//\"" && \
  echo "PS1='\\u@typesetter:\\w\\$ '" >> $PROFILE

# ########################################################################
#
# Download and install typesetting software
#
# ########################################################################
WORKDIR $INSTALL_DIR

ADD "http://lmtx.pragma-ade.nl/install-lmtx/context-linuxmusl.zip" "context.zip"
RUN unzip context.zip -d context

WORKDIR "context"
RUN sh install.sh

# ########################################################################
#
# Download and extract themes
#
# ########################################################################
WORKDIR $THEME_DIR

ADD "https://github.com/DaveJarvis/keenwrite-themes/releases/latest/download/theme-pack.zip" "theme-pack.zip"
RUN unzip theme-pack.zip

# ########################################################################
#
# Remove unnecessary files
#
# ########################################################################
RUN \
  rm -rf "/var/cache" && \
  rm -rf "$CONTEXT_HOME/tex/texmf-context/doc" && \
  rm -f "$THEME_DIR/theme-pack.zip" && \
  rm -f "$FONT_DIR/*.zip" && \
  rm -f "$INSTALL_DIR/context.zip" && \
  find . -type f -name "*.pdf" -exec rm {} \; && \
  find . -type f -name "*.log" -exec rm {} \;

