# ########################################################################
#
# Copyright 2022 White Magic Software, Ltd.
#
# Creates a container image that can run ConTeXt to typeset documents.
#
# ########################################################################

FROM alpine:latest
ENV ENV="/etc/profile"
ENV PROFILE=/etc/profile

ENV INSTALL_DIR=/opt
ENV FONT_DIR=/usr/share/fonts/user
ENV DOC_DIR=/root/text
ENV IMAGE_DIR=/root/images
ENV DOWNLOAD_DIR=/root

ENV CONTEXT_HOME=$INSTALL_DIR/context

RUN apk --update add --no-cache fontconfig curl

# ########################################################################
#
# Download all required dependencies
#
# ########################################################################
WORKDIR $DOWNLOAD_DIR

# Carlito (Calibri replacement)
ADD "https://github.com/googlefonts/carlito/raw/main/fonts/ttf/Carlito-Regular.ttf" "Carlito-Regular.ttf"
ADD "https://github.com/googlefonts/carlito/raw/main/fonts/ttf/Carlito-Bold.ttf" "Carlito-Bold.ttf"
ADD "https://github.com/googlefonts/carlito/raw/main/fonts/ttf/Carlito-Italic.ttf" "Carlito-Italic.ttf"
ADD "https://github.com/googlefonts/carlito/raw/main/fonts/ttf/Carlito-BoldItalic.ttf" "Carlito-BoldItalic.ttf"

# Libre Baskerville
ADD "https://github.com/googlefonts/Libre-Baskerville/blob/master/fonts/ttf/LibreBaskerville-Regular.ttf" "LibreBaskerville-Regular.ttf"
ADD "https://github.com/googlefonts/Libre-Baskerville/blob/master/fonts/ttf/LibreBaskerville-Bold.ttf" "LibreBaskerville-Bold.ttf"
ADD "https://github.com/googlefonts/Libre-Baskerville/blob/master/fonts/ttf/LibreBaskerville-Italic.ttf" "LibreBaskerville-Italic.ttf"

# Open Sans Emoji
ADD "https://github.com/MorbZ/OpenSansEmoji/raw/master/OpenSansEmoji.ttf" "OpenSansEmoji.ttf"

# Underwood Quiet Tab
ADD "https://site.xavier.edu/polt/typewriters/Underwood_Quiet_Tab.ttf" "Underwood_Quiet_Tab.ttf"

# Archives
ADD "https://fonts.google.com/download?family=Courier%20Prime" "courier-prime.zip"
ADD "https://fonts.google.com/download?family=Inconsolata" "inconsolata.zip"
ADD "https://fonts.google.com/download?family=Nunito" "nunito.zip"
ADD "https://fonts.google.com/download?family=Roboto" "roboto.zip"
ADD "https://fonts.google.com/download?family=Roboto%20Mono" "roboto-mono.zip"
ADD "https://github.com/adobe-fonts/source-serif/releases/download/4.004R/source-serif-4.004.zip" "source-serif.zip"
ADD "https://www.omnibus-type.com/wp-content/uploads/Archivo-Narrow.zip" "archivo-narrow.zip"

# Typesetting software
ADD "http://lmtx.pragma-ade.nl/install-lmtx/context-linuxmusl.zip" "context.zip"

# Document themes
ADD "https://github.com/DaveJarvis/keenwrite-themes/releases/latest/download/theme-pack.zip" "theme-pack.zip"

# ########################################################################
#
# Install components, configure system, remove unnecessary files
#
# ########################################################################
WORKDIR $CONTEXT_HOME

RUN \
  mkdir -p "$FONT_DIR" "$DOC_DIR" "$IMAGE_DIR" "$INSTALL_DIR" && \
  echo "export CONTEXT_HOME=\"$CONTEXT_HOME\"" >> $PROFILE && \
  echo "export PATH=\"\$PATH:\$CONTEXT_HOME/tex/texmf-linuxmusl/bin\"" >> $PROFILE && \
  echo "export OSFONTDIR=\"/usr/share/fonts//\"" && \
  echo "PS1='\\u@typesetter:\\w\\$ '" >> $PROFILE && \
  unzip -d $CONTEXT_HOME $DOWNLOAD_DIR/context.zip && \
  unzip -d $INSTALL_DIR $DOWNLOAD_DIR/theme-pack.zip && \
  unzip -j -o -d $FONT_DIR $DOWNLOAD_DIR/courier-prime.zip "*.ttf" && \
  unzip -j -o -d $FONT_DIR $DOWNLOAD_DIR/inconsolata.zip "**/Inconsolata/*.ttf" && \
  unzip -j -o -d $FONT_DIR $DOWNLOAD_DIR/nunito.zip "static/*.ttf" && \
  unzip -j -o -d $FONT_DIR $DOWNLOAD_DIR/roboto.zip "*.ttf" && \
  unzip -j -o -d $FONT_DIR $DOWNLOAD_DIR/roboto-mono.zip "static/*.ttf" && \
  unzip -j -o -d $FONT_DIR $DOWNLOAD_DIR/source-serif.zip "source-serif-4.004/OTF/SourceSerif4-*.otf" && \
  unzip -j -o -d $FONT_DIR $DOWNLOAD_DIR/archivo-narrow.zip "Archivo-Narrow/otf/*.otf" && \
  mv $DOWNLOAD_DIR/*tf $FONT_DIR && \
  fc-cache -f -v && \
  sh install.sh && \
  rm -rf "/var/cache" && \
  rm -f $DOWNLOAD_DIR/*.zip && \
  rm -rf $CONTEXT_HOME/tex/texmf-context/doc && \
  find $CONTEXT_HOME -type f -name "*.pdf" -exec rm {} \; && \
  find $CONTEXT_HOME -type f -name "*.log" -exec rm {} \;

