#!/usr/bin/env bash

# Writes the name for all OTF files found in the current directory or lower

find src/main/resources/fonts -type f \( -name "*otf" -o -name "*ttf" \) -exec \
  fc-scan --format "%{foundry}: %{family}\n" {} \; | uniq | sort

