#!/usr/bin/env bash

# Writes the name for all OTF files found in the current directory or lower

find . -type f -name "*otf" -exec \
  fc-scan --format "%{foundry}: %{family}\n" {} \; | uniq | sort

